name: Paper Trading Bot

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes
  workflow_dispatch:         # manual run bhi possible

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
        run: python dataCollectorGithubAction.py

      - name: Commit logs
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          touch paper_trading_log.txt
          git add paper_trading_log.txt
          git commit -m "update logs" || echo "no changes"
          git push